# Generated by Django 6.0.3 on 2026-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=140)),
                ('tel_number', models.CharField(max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
